### ISSUE TITLE
New tab on search

### ISSUE THREAD

**Issue by reisgabrieljoao** [ronakg/quickr-cscope.vim#9]
Hello,

I just started using the plugin and there's a behavior that I'm not sure if it's a bug or a feature. Whenever I perform a search (e.g. `<leader>s`), a new tab is created with the quickfix window below. Shouldn't the quickfix window appear bellow the tab in which I performed the search?

Regards.

**Comment by ronakg** [comment]
It should open the new window in the same tab. Is it opening a new vim tab and quickfix window inside it?

What do you see when you execute:

`:verbose map <leader>s`

**Comment by reisgabrieljoao** [comment]
Exactly, it opens in a new tab with a quickfix window in the bottom.

```
:verbose map <leader>s
n  ,s            <Plug>(quickr_cscope_symbols)
        Last set from ~/.vim/bundle/quickr-cscope.vim/plugin/quickr-cscope.vim
```

**Comment by ronakg** [comment]
I'll try to look into this sometime next week. If you can reproduce this issue with a minimal vimrc, that would help a lot in debugging.

**Comment by reisgabrieljoao** [comment]
I found the problem. I had the following line in my vimrc:

`set switchbuf=useopen,usetab,newtab`

Removing fixes the problem. Thanks anyway!

**Comment by ronakg** [comment]
Glad you found the issue.
